### ISSUE TITLE
No longer working correctly with Zway 3.2.0

### ISSUE THREAD

**Issue by Vinisz** [bkorda/node-red-contrib-zway#10]
Hi,

Just upgraded to zway 3.2.0 and the node is no longer working correctly.
Data is sent out from node-red to Zway, no problems there but,
No data is received from Zway to node-red node anymore.
Can you investigate ?

**Comment by bkorda** [comment]
Sorry, I have no soft and hardware to test, need to find a new device

**Comment by Vinisz** [comment]
What do you need ? zway device or node-red ?

**Comment by bkorda** [comment]
Have no device

**Comment by bkorda** [comment]
fixed in node-red-contrib-zway@1.0.0

**Comment by Vinisz** [comment]
Not fixed, just tried on latest node-red , and latest zway, still crashes node-red

![image](https://user-images.githubusercontent.com/49644964/145801679-31b9af75-e305-4f46-9027-c1d6d031f37b.png)

**Comment by Vinisz** [comment]
@bkorda , not sure how to re-open this, but would be glad if you can fix this

**Comment by bkorda** [comment]
Answered you in a pullrequest.
